# Generated by Django 5.0.3 on 2024-04-14 05:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=100)),
                ('Event_Title', models.TextField()),
                ('Event_Venue', models.CharField(default='SCAS', max_length=1000)),
                ('Event_Start_Date', models.DateField()),
                ('Event_End_Date', models.DateField()),
                ('Event_Start_Time', models.TimeField(choices=[(datetime.time(0, 0), '12:00 AM'), (datetime.time(1, 0), '1:00 AM'), (datetime.time(2, 0), '2:00 AM'), (datetime.time(3, 0), '3:00 AM'), (datetime.time(4, 0), '4:00 AM'), (datetime.time(5, 0), '5:00 AM'), (datetime.time(6, 0), '6:00 AM'), (datetime.time(7, 0), '7:00 AM'), (datetime.time(8, 0), '8:00 AM'), (datetime.time(9, 0), '9:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(15, 0), '3:00 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(17, 0), '5:00 PM'), (datetime.time(18, 0), '6:00 PM'), (datetime.time(19, 0), '7:00 PM'), (datetime.time(20, 0), '8:00 PM'), (datetime.time(21, 0), '9:00 PM'), (datetime.time(22, 0), '10:00 PM'), (datetime.time(23, 0), '11:00 PM')])),
                ('Event_End_Time', models.TimeField(choices=[(datetime.time(0, 0), '12:00 AM'), (datetime.time(1, 0), '1:00 AM'), (datetime.time(2, 0), '2:00 AM'), (datetime.time(3, 0), '3:00 AM'), (datetime.time(4, 0), '4:00 AM'), (datetime.time(5, 0), '5:00 AM'), (datetime.time(6, 0), '6:00 AM'), (datetime.time(7, 0), '7:00 AM'), (datetime.time(8, 0), '8:00 AM'), (datetime.time(9, 0), '9:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(15, 0), '3:00 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(17, 0), '5:00 PM'), (datetime.time(18, 0), '6:00 PM'), (datetime.time(19, 0), '7:00 PM'), (datetime.time(20, 0), '8:00 PM'), (datetime.time(21, 0), '9:00 PM'), (datetime.time(22, 0), '10:00 PM'), (datetime.time(23, 0), '11:00 PM')])),
                ('Broucher', models.ImageField(upload_to='broucher')),
                ('Chief_Patrons', models.TextField(default='Dr. MARIAZEENA JOHNSON, CHANCELLOR| Dr. MARIE JOHNSON, PRESIDENT| Ms. MARIA CATHERINE JAYAPRIYA,VICE PRESIDENT')),
                ('Patrons', models.TextField(default='Dr. T. SASIPRABA, VICE CHANCELLOR')),
                ('Convenors', models.TextField(default='Format:Name1,Name 2')),
                ('Facult_Coordinator', models.TextField(default='Format:Name1,Name 2')),
                ('Student_Coordinator', models.TextField(default='Format:Name1,Name 2')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('denial_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_edit_event', 'Can edit event')],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Register_No', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=1000)),
                ('Department', models.CharField(max_length=1000)),
                ('Class_No', models.CharField(max_length=1000)),
                ('Event_Name', models.CharField(max_length=1000)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
    ]
