# Generated by Django 5.0.3 on 2024-04-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='Email',
            field=models.EmailField(default='@gmail.com', max_length=254),
        ),
    ]
