# Generated by Django 5.0.3 on 2024-04-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_eventregistration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
