# Generated by Django 5.0.3 on 2024-04-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_eventregistration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='QR_Code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
