# Generated by Django 5.0.3 on 2024-04-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_eventregistration_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='qr_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
