# Generated by Django 5.0.3 on 2024-04-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_eventregistration_qr_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('NOT IN', 'NOT IN'), ('IN', 'IN')], default='NOT_IN', max_length=10),
        ),
    ]
