# Generated by Django 5.0.3 on 2024-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_eventregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='Phone_No',
            field=models.CharField(default='-', max_length=1000),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='Section',
            field=models.CharField(default='A1', max_length=1000),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='Specialization',
            field=models.CharField(default='Null', max_length=1000),
        ),
    ]
