# Generated by Django 5.0.3 on 2024-04-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_eventregistration_phone_no_eventregistration_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='Phone_No',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Section',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Specialization',
            field=models.CharField(max_length=1000),
        ),
    ]
