# Generated by Django 5.0.3 on 2024-04-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_eventregistration_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='Section',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('B1', 'B1'), ('B2', 'B2')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='Specialization',
            field=models.CharField(choices=[('B.E CSE - Artificial Intelligence', 'B.E CSE - Artificial Intelligence'), ('B.E CSE - Data Science', 'B.E CSE - Data Science'), ('B.E CSE - Internet of Things', 'B.E CSE - Internet of Things'), ('B.E CSE - Artificial Intelligence and Robotics', 'B.E CSE - Artificial Intelligence and Robotics'), ('B.E CSE - Artificial Intelligence and Machine Learning', 'B.E CSE - Artificial Intelligence and Machine Learning'), ('B.E CSE - Block Chain Technology', 'B.E CSE - Block Chain Technology'), ('B.E CSE - Cyber Security', 'B.E CSE - Cyber Security')], max_length=1000),
        ),
    ]
