# Generated by Django 5.0.3 on 2024-04-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_eventregistration_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1000),
        ),
    ]
