# Generated by Django 5.0.3 on 2024-04-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_eventregistration_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='Specialization',
            field=models.CharField(choices=[('B.E CSE - Artificial Intelligence', 'B.E CSE - Artificial Intelligence'), ('B.E CSE - Data Science', 'B.E CSE - Data Science'), ('B.E CSE - Internet of Things', 'B.E CSE - Internet of Things'), ('B.E CSE - Artificial Intelligence and Robotics', 'B.E CSE - Artificial Intelligence and Robotics'), ('B.E CSE - Artificial Intelligence and Machine Learning', 'B.E CSE - Artificial Intelligence and Machine Learning'), ('B.E CSE - Block Chain Technology', 'B.E CSE - Block Chain Technology'), ('B.E CSE - Cyber Security', 'B.E CSE - Cyber Security'), ('Others', 'Others')], max_length=1000),
        ),
    ]
