# Generated by Django 5.0.3 on 2024-04-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_eventregistration_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='Class_No',
        ),
    ]
