# Generated by Django 5.0.3 on 2024-04-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_eventregistration_class_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='Class_No',
            field=models.CharField(default='320', max_length=1000),
        ),
    ]
