# Generated by Django 5.0.3 on 2024-04-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_eventregistration_class_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='Class_No',
        ),
    ]
