# Generated by Django 5.0.3 on 2024-04-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_eventregistration_class_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('Register_No', 'Event_Name')},
        ),
    ]
